name: Upload test artifacts

description: Upload various artifacts produced by our testing process

inputs:
  use-gha:
    description: If set to any value, upload GHA. Otherwise upload to S3.
    required: false
  file-suffix:
    description: |
      Suffix to add to the filename of the artifacts. This should include the
      workflow job id, see [Job id in artifacts].
    required: true

runs:
  using: composite
  steps:
    # Mac/Linux zip
    - name: Zip JSONs for upload
      if: runner.os != 'Windows' && !inputs.use-gha
      shell: bash
      env:
        FILE_SUFFIX: ${{ inputs.file-suffix }}
      run: |
        # Remove any previous test jsons if they exist
        rm -f test-jsons-*.zip
        zip -r "test-jsons-${FILE_SUFFIX}.zip" test -i '*.json'

    - name: Zip test reports for upload
      if: runner.os != 'Windows' && !inputs.use-gha
      shell: bash
      env:
        FILE_SUFFIX: ${{ inputs.file-suffix }}
      run: |
        # Remove any previous test reports if they exist
        rm -f test-reports-*.zip
        zip -r "test-reports-${FILE_SUFFIX}.zip" test -i '*.xml'

    # Windows zip
    - name: Zip JSONs for upload
      if: runner.os == 'Windows' && !inputs.use-gha
      shell: powershell
      env:
        FILE_SUFFIX: ${{ inputs.file-suffix }}
      run: |
        # -ir => recursive include all files in pattern
        7z a "test-jsons-$Env:FILE_SUFFIX.zip" -ir'!test\*.json'

    - name: Zip test reports for upload
      if: runner.os == 'Windows' && !inputs.use-gha
      shell: powershell
      env:
        FILE_SUFFIX: ${{ inputs.file-suffix }}
      run: |
        # -ir => recursive include all files in pattern
        7z a "test-reports-$Env:FILE_SUFFIX.zip" -ir'!test\*.xml'

    # S3 upload
    - name: Store Test Downloaded JSONs on S3
      uses: seemethere/upload-artifact-s3@v4
      if: ${{ !inputs.use-gha }}
      with:
        retention-days: 14
        if-no-files-found: warn
        path: test-jsons-*.zip

    - name: Store Test Reports on S3
      uses: seemethere/upload-artifact-s3@v4
      if: ${{ !inputs.use-gha }}
      with:
        retention-days: 14
        if-no-files-found: error
        path: test-reports-*.zip

    # GHA upload
    - name: Store Test Downloaded JSONs on Github
      uses: actions/upload-artifact@v2
      if: inputs.use-gha
      with:
        # Add the run attempt, see [Artifact run attempt]
        name: test-jsons-runattempt${{ github.run_attempt }}-${{ inputs.file-suffix }}.zip
        retention-days: 14
        if-no-files-found: warn
        path: test/**/*.json

    - name: Store Test Reports on Github
      uses: actions/upload-artifact@v2
      if: inputs.use-gha
      with:
        # Add the run attempt, see [Artifact run attempt]
        name: test-reports-runattempt${{ github.run_attempt }}-${{ inputs.file-suffix }}.zip
        retention-days: 14
        if-no-files-found: error
        path: test/**/*.xml
