name: Teardown ROCm host

description: Teardown ROCm host for CI

runs:
  using: composite
  steps:
    - name: Kill containers, clean up images
      if: always()
      shell: bash
      run: |
        # ignore expansion of "docker ps -q" since it could be empty
        # shellcheck disable=SC2046
        docker stop $(docker ps -q) || true
        # Prune all of the docker containers
        docker container prune -f
        # Prune everything docker if there are more than 10 images (~200GB).
        # This is easier than using a time filter, e.g., "until=24h".
        image_count=$(docker images | wc -l)
        if [[ ${image_count} -gt 10 ]]; then
            echo "Purging all docker caches"
            docker system prune -af
        else
            echo "Will not purge docker, only ${image_count} images found"
        fi
