name: Pull docker image

description: pull a specific docker image

inputs:
  docker-image:
    description: the image to pull
    required: true

runs:
  using: composite
  steps:
    - name: Pull Docker image
      shell: bash
      env:
        DOCKER_IMAGE: ${{ inputs.docker-image }}
      run: |
        retry () { "$@"  || (sleep 1 && "$@") || (sleep 2 && "$@") }
        retry docker pull "${DOCKER_IMAGE}"
