name: Update PyTorch Labels in S3

on:
  label:
  workflow_dispatch:

concurrency:
  group: 1
  cancel-in-progress: true

jobs:
  update-labels-in-S3:
    runs-on: ubuntu-18.04
    if: ${{ github.repository == 'pytorch/pytorch' }}
    steps:
      - name: Checkout PyTorch
        uses: zhouzhuojie/checkout@05b13c9a0d21f08f6d5e64a1d5042246d13619d9
      - name: Update PyTorch labels list in S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_OSSCI_METRICS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_OSSCI_METRICS_SECRET_ACCESS_KEY }}
        run: |
          python3 -m pip install boto3==1.19.12
          .github/scripts/export_pytorch_labels.py
